<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Project;

class ProjectSeeder extends Seeder
{
    public function run()
    {
        Project::insert([
            [
                'id' => 'PRO-24-001',
                'company_id' => 1,
                'date' => '2024-01-01',
                'name' => 'Project A',
                'billing' => '50000000',
                'cost_estimate' => '40000000',
                'margin' => '10000000',
                'percent' => '20%',
                'status_cost_progress' => '50%',
                'file' => 'file_project_a.pdf',
                'status' => Project::PENDING,
                'user_id' => 1,
            ],
            [
                'id' => 'PRO-24-002',
                'company_id' => 2,
                'date' => '2024-02-01',
                'name' => 'Project B',
                'billing' => '60000000',
                'cost_estimate' => '45000000',
                'margin' => '15000000',
                'percent' => '25%',
                'status_cost_progress' => '40%',
                'file' => 'file_project_b.pdf',
                'status' => Project::PENDING,
                'user_id' => 1,
            ],
            [
                'id' => 'PRO-24-003',
                'company_id' => 1,
                'date' => '2024-03-01',
                'name' => 'Project C',
                'billing' => '70000000',
                'cost_estimate' => '50000000',
                'margin' => '20000000',
                'percent' => '30%',
                'status_cost_progress' => '60%',
                'file' => 'file_project_c.pdf',
                'status' => Project::PENDING,
                'user_id' => 2,
            ],
            [
                'id' => 'PRO-24-004',
                'company_id' => 2,
                'date' => '2024-04-01',
                'name' => 'Project D',
                'billing' => '80000000',
                'cost_estimate' => '60000000',
                'margin' => '20000000',
                'percent' => '25%',
                'status_cost_progress' => '70%',
                'file' => 'file_project_d.pdf',
                'status' => Project::PENDING,
                'user_id' => 1,
            ],
            [
                'id' => 'PRO-24-005',
                'company_id' => 1,
                'date' => '2024-05-01',
                'name' => 'Project E',
                'billing' => '90000000',
                'cost_estimate' => '70000000',
                'margin' => '20000000',
                'percent' => '22%',
                'status_cost_progress' => '80%',
                'file' => 'file_project_e.pdf',
                'status' => Project::PENDING,
                'user_id' => 2,
            ],
            [
                'id' => 'PRO-24-006',
                'company_id' => 2,
                'date' => '2024-06-01',
                'name' => 'Project F',
                'billing' => '100000000',
                'cost_estimate' => '85000000',
                'margin' => '15000000',
                'percent' => '15%',
                'status_cost_progress' => '90%',
                'file' => 'file_project_f.pdf',
                'status' => Project::PENDING,
                'user_id' => 1,
            ],
            [
                'id' => 'PRO-24-007',
                'company_id' => 1,
                'date' => '2024-07-01',
                'name' => 'Project G',
                'billing' => '110000000',
                'cost_estimate' => '90000000',
                'margin' => '20000000',
                'percent' => '18%',
                'status_cost_progress' => '65%',
                'file' => 'file_project_g.pdf',
                'status' => Project::PENDING,
                'user_id' => 2,
            ],
            [
                'id' => 'PRO-24-008',
                'company_id' => 2,
                'date' => '2024-08-01',
                'name' => 'Project H',
                'billing' => '120000000',
                'cost_estimate' => '100000000',
                'margin' => '20000000',
                'percent' => '20%',
                'status_cost_progress' => '75%',
                'file' => 'file_project_h.pdf',
                'status' => Project::PENDING,
                'user_id' => 1,
            ],
            [
                'id' => 'PRO-24-009',
                'company_id' => 1,
                'date' => '2024-09-01',
                'name' => 'Project I',
                'billing' => '130000000',
                'cost_estimate' => '105000000',
                'margin' => '25000000',
                'percent' => '25%',
                'status_cost_progress' => '85%',
                'file' => 'file_project_i.pdf',
                'status' => Project::PENDING,
                'user_id' => 2,
            ],
            [
                'id' => 'PRO-24-010',
                'company_id' => 2,
                'date' => '2024-10-01',
                'name' => 'Project J',
                'billing' => '140000000',
                'cost_estimate' => '110000000',
                'margin' => '30000000',
                'percent' => '28%',
                'status_cost_progress' => '95%',
                'file' => 'file_project_j.pdf',
                'status' => Project::PENDING,
                'user_id' => 1,
            ],
        ]);
    }
}
